name: Waka Readme

on:
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_COMMIT: "True"
          SHOW_LANGUAGE: "False"
          SHOW_EDITORS: "False"
          SHOW_OS: "False"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_PROJECTS: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_SHORT_INFO: "False"
          IGNORED_REPOS: "MyShop-ecommerce"
          SHOW_LOC_CHART: "False"
      
          
          
            
